version: "2"
services:
    mongo:
        image: 'mongo:latest'
        ports:
            - '27018:27017'
        networks:
            - myapp
    
    mongo2:
        image: 'mongo:latest'
        ports:
            - '27019:27017'
        networks:
            - myapp2
    
    driver1:
        build: ./db-drivers/driver_1/
        ports:
            - '8081:8080'
        networks:
            - myapp
        depends_on:
            - mongo
    
    driver2:
        build: ./db-drivers/driver_2/
        ports:
            - '8082:8080'
        networks:
            - myapp2
        depends_on:
            - mongo2

    frontend:
        build: ./front-end/
        ports:
            - '4201:4200'
        volumes:
            - './front-end/frontend:/app'
            - '/app/node_modules'
        networks:
            - front-end
        depends_on: 
            - middleware
    
    middleware:
        build:
            ./middle-layer/
        ports:
            - '8080:8080'
        depends_on: 
            - driver1
            - driver2
        networks:
            - front-end
            - myapp
            - myapp2

networks:
    myapp:
        driver: bridge
    myapp2:
        driver: bridge
    front-end:
        driver: bridge