version: "2"
services:
    mongo:
        image: 'mongo:latest'
        networks:
            - myapp
        restart: unless-stopped
    
    mongo2:
        image: 'mongo:latest'
        networks:
            - myapp2
        restart: unless-stopped
    
    driver1:
        build: ./db-drivers/driver_1/
        networks:
            - myapp
        depends_on:
            - mongo
        restart: unless-stopped
    
    driver2:
        build: ./db-drivers/driver_2/
        networks:
            - myapp2
        depends_on:
            - mongo2
        restart: unless-stopped

    frontend:
        build: ./front-end/
        ports:
            - '4200:4200'
        volumes:
            - './front-end/frontend:/app'
            - '/app/node_modules'
        networks:
            - front-end
        depends_on: 
            - middleware
        restart: unless-stopped
    
    middleware:
        build:
            ./middle-layer/
        ports:
            - '8080:8080'
        depends_on: 
            - driver1
            - driver2
        networks:
            - front-end
            - myapp
            - myapp2
        restart: unless-stopped

networks:
    myapp:
        driver: bridge
    myapp2:
        driver: bridge
    front-end:
        driver: bridge